name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Cache toolchain
        uses: actions/cache@v3
        with:
          path: cache
          key: toolchain-${{ hashFiles('Makefile') }}
      
      - name: Build firmware
        run: |
          docker run --rm -v ${{ github.workspace }}:/opt/nodemcu-firmware marcelstoer/nodemcu-build build
      
      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: nodemcu-firmware
          path: bin/
