name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build firmware
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/opt/nodemcu-firmware \
            marcelstoer/nodemcu-build build
      
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: nodemcu-firmware
          path: bin/
